module.exports = {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    VERIFIED: 'VERIFIED',
    UNVERIFIED: 'UNVERIFIED',
    TRUE: 'TRUE',
    FALSE: 'FALSE',
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
}